services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"  # Command to install dependencies
    startCommand: "gunicorn app:app"  # Gunicorn to run Flask in production
    plan: free  # Free plan for low-traffic apps
    autoDeploy: true  # Auto deploy whenever there's a push to the default branch
    envVars:
      - key: FLASK_ENV
        value: production  # Set the environment to production for optimized performance
      - key: PORT
        value: "10000"  # Specify the port Render will use
